### PR TITLE
Additional max hp pool & numpad enter key

### PR DESCRIPTION
**Pull request by DarKDinDoN**

### CODE REVIEW

**Comment by DarKDinDoN** [comment]
Fix for https://github.com/schlosrat/token-health/issues/48 + numpad enter key

**Comment by DarKDinDoN** [comment]
@schlosrat Hey, hope you are well.
Is this OK with you? Can you review and hopefully merge this ?

**Comment by schlosrat** [comment]
> @schlosrat Hey, hope you are well.
> Is this OK with you? Can you review and hopefully merge this ?

Hey DarKDinDoN, I see you've been busy solving this. I've been a bit swamped lately but will take a look soon. I want to make sure I understand the fix and that it doesn't collide with some other stuff I've been doing. Thanks for your effort. I'll get this in soon.

**Comment by schlosrat** [comment]
@DarKDinDoN, I've folded in your changes dealing with ALT_MAX_HITPOINTS_ATTRIBUTE_1 and ALT_MAX_HITPOINTS_ATTRIBUTE_2. Sorry for the delay, this was complicated by collisions with some other work I was doing to fix how settings get done.

I've just started looking at the numpad functionality. My initial concern there is that the existing hotkey capability allows customization at the user level and so it's quite possible that some other key could be set by a user. This could lead to confusion since the numpad settings are not configurable. Perhaps a better approach is to optionally allow configuration of a second set of keys? That way users that want it can have the four basic functions triggered with two sets of options (which would work I think for both Enter keys), and those that are fine with just one option can pick what they like and leave it at that.

Your thoughts?

**Comment by DarKDinDoN** [comment]
@schlosrat Hey, Thx for the review.
Alt hitpoints are working great!

As for the numpad Enter key, you are right. Better not making things confusing for users.
It was more about qol than a real feature.

**Pull request closed without merging**
